### ISSUE TITLE
Feature Request: support arrays of same item definition in sample

### ISSUE THREAD

**Issue by karel-rehor** [bonitoo-io/virtual-device#16]
For some simulations it can be useful to have an array of the same item definition.  For example a bar with ultrasonic sensors that measure the transverse profile or a roadway.  Such a bar could have 30 sensors spaced at 10cm intervals.  

Currently adding the same item definition in the config more than once, leads to only one instance of that item being created. 

e.g.

```
---
ttl: 10000
broker:
  host: 52.53.192.249
  port: 8883
  auth:
    username: tester
    password: changeit
  tls:
    trustStore: "./scripts/keys/brokerTrust.jks"
    trustPass: "ENCqTJZQarWDANjbiKQRH1R5/Dw3jNtSIYq12fIt67sIPEAAAAQmi6eCz/B3DynfmBHkC30s9n9/ynDhlcNo2yDA7ma90k="
items:
  - name: "transverse"
    type: "Double"
    label: "cm"
    max: 25.0
    min: 5.0
    period: 1
  - name: "verticalAccel"
    type: "Double"
    label: "gForce"
    max: 2.0
    min: -2.0
    period: 1
  - name: "speed"
    type: "Double"
    label: "kph"
    max: 120.0
    min: 0.0
    period: 7
samples:
  - id: "roadData"
    name: "roadData"
    topic: "test/rdata"
    items:
      - "transverse"
      - "transverse"
      - "transverse"
      - "transverse"
      - "transverse"
      - "verticalAccel"
      - "speed"
devices:
  - id: "roadSampler"
    name: "Road Sampler 01"
    description: "typical road sampler"
    interval: 1000
    jitter: 0
    count: 1
    samples:
      - "roadData"

```
