### ISSUE TITLE
prec in configuration for double types seems to be ignored

### ISSUE THREAD

**Issue by karel-rehor** [bonitoo-io/virtual-device#6]
It seems `prec` in the double item type is not recognized. 

```
items:
  - name: "tension"
    type: "Double"
    label: "bar"
    max: 2.0
    min: -1.0
    period: 1
    prec: 3
```

```
Payload {
  "id" : "31f959a4-61d0-42ac-9682-99905d6f69ee",
  "timestamp" : 1685004440243,
  "bar" : -0.03838613887781117,
  "nutcount" : 25
}
```

**Comment by karel-rehor** [comment]
_Can't Reproduce_

commit 8c36a7e93981f0e0ef92f3a1c9d30e47c4267294 

Note the above branch is about to be merged. 

Prec seems to work for me now as expected.  I suspect that last week there was a confusion when using config.yml files.

**Comment by karel-rehor** [comment]
Further info as to why closed. 

```yaml
---
ttl: 10000
broker:
  host: localhost
  port: 1883
  auth:
    username: fred
    password: changeit
items:
  - name: "wumpus"
    type: "Double"
    label: "test"
    max: 10.0
    min: -10.0
    period: 1
    prec: 3
  - name: "tension"
    type: "Double"
    label: "bar"
    max: 2.0
    min: -1.0
    period: 1
    prec: 5
samples:
  - id: "random"
    name: "foo"
    topic: "test/foo"
    items:
      - "wumpus"
      - "tension"
  - id: "random"
    name: "cmps"
    topic: "test/bar"
    items:
      - name: "flowRate"
        label: "cmps"
        type: Double
        max: 30
        min: 5
        period: 2
        prec: 2
devices:
  - id: "random"
    name: "Testing Prec Device 01"
    description: "testing precision device configuration"
    interval: 1000
    jitter: 0
    count: 1
    samples:
      - "foo"
      - "cmps"

```

Run as 

```bash
$ java -Drunner.conf=src/test/resources/testRunnerWithPrec.yml -jar target/virtual-device-0.1-SNAPSHOT-8c36a7e.jar 
```

From listener console

```
Payload {
  "id" : "a20ede49-3f78-4240-9422-e9dca169f4a5",
  "timestamp" : 1685362044106,
  "bar" : -0.03455,
  "test" : -4.277
}
Callback on publish MqttPublish{topic=test/bar, payload=100byte, qos=AT_MOST_ONCE, retain=false}
Payload {
  "id" : "5167a8fe-cac0-4870-a54c-1dd20aa9d344",
  "timestamp" : 1685362044108,
  "cmps" : 11.75
}


```
